# importing all the lists from the 'conjunto_de_elfos' folder.

from conjunto_de_elfos import conj_1 as cj1
from conjunto_de_elfos import conj_2 as cj2
from conjunto_de_elfos import conj_3 as cj3
from conjunto_de_elfos import conj_4 as cj4
from conjunto_de_elfos import conj_5 as cj5
from conjunto_de_elfos import conj_6 as cj6
from conjunto_de_elfos import conj_7 as cj7
from conjunto_de_elfos import conj_8 as cj8
from conjunto_de_elfos import conj_9 as cj9

# simple test of function:
# the first 4 lists from the first two cj's are selected and then conpared to see wich is bigger.
asoma1 = sum(cj1.int_elfoA)
asoma2 = sum(cj1.int_elfoB)
asoma3 = sum(cj1.int_elfoC)
asoma4 = sum(cj1.int_elfoD)

bsoma1 = sum(cj2.int_elfoa)
bsoma2 = sum(cj2.int_elfob)
bsoma3 = sum(cj2.int_elfoc)
bsoma4 = sum(cj2.int_elfod)

# 'asoma' reffers to all the lists from the 'conj_1.py' and 'bsoma' reffers to all lists from 'conj_2.py'

bsoma5 = sum(cj2.int_elfoe)
bsoma6 = sum(cj2.int_elfof)
bsoma7 = sum(cj2.int_elfog)
bsoma8 = sum(cj2.int_elfoh)
bsoma9 = sum(cj2.int_elfoi)
bsoma10 = sum(cj2.int_elfoj)
bsoma11 = sum(cj2.int_elfoJK)
bsoma12 = sum(cj2.int_elfok)
bsoma13 = sum(cj2.int_elfol)
bsoma14 = sum(cj2.int_elfom)
bsoma15 = sum(cj2.int_elfon)
bsoma16 = sum(cj2.int_elfoo)
bsoma17 = sum(cj2.int_elfop)
bsoma18 = sum(cj2.int_elfoq)
bsoma19 = sum(cj2.int_elfor)
bsoma20 = sum(cj2.int_elfos)
bsoma21 = sum(cj2.int_elfot)
bsoma22 = sum(cj2.int_elfou)
bsoma23 = sum(cj2.int_elfov)
bsoma24 = sum(cj2.int_elfow)
bsoma25 = sum(cj2.int_elfox)
boma26 = sum(cj2.int_elfoy)
bsoma27 = sum(cj2.int_elfoz)

asoma5 = sum(cj1.int_elfoE)
asoma6 = sum(cj1.int_elfoF)
asoma7 = sum(cj1.int_elfoG)
asoma8 = sum(cj1.int_elfoH)
asoma9 = sum(cj1.int_elfoI)
asoma10 = sum(cj1.int_elfoJ)
asoma11 = sum(cj1.int_elfoK)
asoma12 = sum(cj1.int_elfoL)
asoma13 = sum(cj1.int_elfoM)
asoma14 = sum(cj1.int_elfoN)
asoma15 = sum(cj1.int_elfoO)
asoma16 = sum(cj1.int_elfoP)
asoma17 = sum(cj1.int_elfoQ)
asoma18 = sum(cj1.int_elfoR)
asoma19 = sum(cj1.int_elfoS)
asoma20 = sum(cj1.int_elfoU)
asoma21 = sum(cj1.int_elfoV)
asoma22 = sum(cj1.int_elfoW)
asoma23 = sum(cj1.int_elfoX)
asoma24 = sum(cj1.int_elfoY)
asoma25 = sum(cj1.int_elfoZ)

csoma1 = sum(cj3.int_aelfo)
csoma2 = sum(cj3.int_belfo)
csoma3 = sum(cj3.int_celfo)
csoma4 = sum(cj3.int_delfo)
csoma5 = sum(cj3.int_felfo)
csoma6 = sum(cj3.int_gelfo)
csoma7 = sum(cj3.int_helfo)
csoma8 = sum(cj3.int_jelfo)
csoma9 = sum(cj3.int_kelfo)
csoma10 = sum(cj3.int_lelfo)
csoma11 = sum(cj3.int_melfo)
csoma12 = sum(cj3.int_nelfo)
csoma13 = sum(cj3.int_oelfo)
csoma14 = sum(cj3.int_oertes)
csoma15 = sum(cj3.int_pelfo)
csoma16 = sum(cj3.int_qelfo)
csoma17 = sum(cj3.int_relfo)
csoma18 = sum(cj3.int_selfo)
csoma19 = sum(cj3.int_telfo)
csoma20 = sum(cj3.int_uelfo)
csoma21 = sum(cj3.int_velfo)
csoma22 = sum(cj3.int_welfo)
csoma23 = sum(cj3.int_xelfo)
csoma24 = sum(cj3.int_yelfo)
csoma25 = sum(cj3.int_zelfo)

dsoma1 = sum(cj4.int_ofelA)
dsoma2 = sum(cj4.int_ofelB)
dsoma3 = sum(cj4.int_ofelC)
dsoma4 = sum(cj4.int_ofelD)
dsoma5 = sum(cj4.int_ofelE)
dsoma6 = sum(cj4.int_ofelF)
dsoma7 = sum(cj4.int_ofelG)
dsoma8 = sum(cj4.int_ofelH)
dsoma9 = sum(cj4.int_ofelI)
dsoma10 = sum(cj4.int_ofelJ)
dsoma11 = sum(cj4.int_ofelK)
dsoma12 = sum(cj4.int_ofélia)
dsoma13 = sum(cj4.int_ofelL)
dsoma14 = sum(cj4.int_ofelM)
dsoma15 = sum(cj4.int_ofelN)
dsoma16 = sum(cj4.int_ofelO)
dsoma17 = sum(cj4.int_ofelP)
dsoma18 = sum(cj4.int_ofelQ)
dsoma19 = sum(cj4.int_ofelR)
dsoma20 = sum(cj4.int_ofelS)
dsoma21 = sum(cj4.int_ofelT)
dsoma22 = sum(cj4.int_ofelU)
dsoma23 = sum(cj4.int_ofelV)
dsoma24 = sum(cj4.int_ofelW)
dsoma25 = sum(cj4.int_ofelX)
dsoma26 = sum(cj4.int_ofelY)
dsoma27 = sum(cj4.int_ofelZ)

